//package com.example.demo.repositories;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//import com.example.demo.model.Transaction;
//import com.example.demo.model.User;
//
//@DynamoDBTable(tableName = "Transactions")
//public class ExtendedTransaction extends Transaction {
//
//    private String userId;
//
//    @DynamoDBHashKey
//    public String getUserId() {
//        return userId;
//    }
//
//    public void setUserId(String userId) {
//        this.userId = userId;
//    }
//}
